#requires -Version 5.1
[CmdletBinding()]
param([switch]$CheckOnly, [string]$PreviewPath = '')
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms, System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
$admin = (New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $admin -and -not $CheckOnly -and -not $PreviewPath) {
    try { Start-Process -FilePath "$env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe" -Verb RunAs -WindowStyle Hidden -ArgumentList ('-NoProfile -STA -ExecutionPolicy Bypass -File "' + $PSCommandPath + '"') }
    catch { [System.Windows.Forms.MessageBox]::Show('Autorizzazione amministratore annullata. Nessun programma installato.','M3PRO Setup') | Out-Null }
    exit
}
$engineBase64 = '77u/I3JlcXVpcmVzIC1WZXJzaW9uIDUuMQo8IwpNM1BSTyAtIEluc3RhbGxhemlvbmUgbnVvdmEgbWFjY2hpbmEgV2luZG93cyB4NjQuClNjYXJpY2EgU0VNUFJFIGxhIHJlbGVhc2Ugc3RhYmxlIGFwcHJvdmF0YSBkYWwgcG9ydGFsZSAobm9uIGlsIHJhbW8gR2l0KS4KVXNvOiBwb3dlcnNoZWxsIC1FeGVjdXRpb25Qb2xpY3kgQnlwYXNzIC1GaWxlIC5cSU5TVEFMTEEtTUVGRi5wczEKVmVyaWZpY2Egc2VuemEgaW5zdGFsbGFyZTogYWdnaXVuZ2VyZSAtQ2hlY2tPbmx5ClVuYSBjYXJ0ZWxsYSBHaXQgYXBwZW5hIGNsb25hdGEgdmllbmUgYXJjaGl2aWF0YSBpbnRlZ3JhbG1lbnRlIHByaW1hIGRlbCBzZXR1cC4KVW4gTTMgZ2lhJyBjb25maWd1cmF0byBkZXZlIHVzYXJlIFVwZGF0ZTogcXVlc3RvIGluc3RhbGxlciBub24gbG8gc292cmFzY3JpdmUuCiM+CltDbWRsZXRCaW5kaW5nKCldCnBhcmFtKAogICAgW3N3aXRjaF0kQ2hlY2tPbmx5LAogICAgW3N3aXRjaF0kQ2hlY2tsaXN0T25seSwKICAgIFtzdHJpbmddJFN0YXR1c0ZpbGUgPSAnJywKICAgIFtzdHJpbmddJENvbmZpZ0ZpbGUgPSAnJywKICAgIFtzd2l0Y2hdJFNraXBFeHRlcm5hbFRvb2xzCikKJEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICdTdG9wJwokUHJvZ3Jlc3NQcmVmZXJlbmNlID0gJ1NpbGVudGx5Q29udGludWUnCiRJbnN0YWxsUm9vdCA9ICdDOlxNRUZGJwokRmVlZCA9ICdodHRwczovL3BjLW5ldHdvcmstc2Nhbi5lbWVyZ2VudC5ob3N0L2FwaS91cGRhdGUtZmVlZCcKJFV0ZjggPSBOZXctT2JqZWN0IFN5c3RlbS5UZXh0LlVURjhFbmNvZGluZygkZmFsc2UpCiRCb290c3RyYXBTb3VyY2UgPSBbSU8uRmlsZV06OlJlYWRBbGxUZXh0KCRQU0NvbW1hbmRQYXRoKQpbTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sID0gW05ldC5TZWN1cml0eVByb3RvY29sVHlwZV06OlRsczEyCiRXb3JrID0gSm9pbi1QYXRoICRlbnY6VEVNUCAoJ00zLVNldHVwLScgKyBbZ3VpZF06Ok5ld0d1aWQoKS5Ub1N0cmluZygnTicpKQoKZnVuY3Rpb24gV3JpdGUtVXRmOChbc3RyaW5nXSRQYXRoLCBbc3RyaW5nXSRUZXh0KSB7CiAgICBbSU8uRmlsZV06OldyaXRlQWxsVGV4dCgkUGF0aCwgJFRleHQsICRVdGY4KQp9CmZ1bmN0aW9uIFJ1bi1DaGVja2VkKFtzdHJpbmddJEV4ZSwgW3N0cmluZ1tdXSRBcmd1bWVudHMpIHsKICAgICRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAnQ29udGludWUnICMgV2luZG93cyBQb3dlclNoZWxsOiBzdGRlcnIgbm9uIGltcGxpY2EgZXhpdCBjb2RlICE9IDAuCiAgICAmICRFeGUgQEFyZ3VtZW50cwogICAgaWYgKCRMQVNURVhJVENPREUgLW5lIDApIHsgdGhyb3cgIkNvbWFuZG8gZmFsbGl0bzogJEV4ZSAoY29kaWNlICRMQVNURVhJVENPREUpLiIgfQp9CmZ1bmN0aW9uIFJlZnJlc2gtUGF0aCB7CiAgICAkZW52OlBhdGggPSBbRW52aXJvbm1lbnRdOjpHZXRFbnZpcm9ubWVudFZhcmlhYmxlKCdQYXRoJywnTWFjaGluZScpICsgJzsnICsgW0Vudmlyb25tZW50XTo6R2V0RW52aXJvbm1lbnRWYXJpYWJsZSgnUGF0aCcsJ1VzZXInKQp9CmZ1bmN0aW9uIEluc3RhbGwtV2luZ2V0KFtzdHJpbmddJElkKSB7CiAgICBXcml0ZS1Ib3N0ICJJbnN0YWxsYXppb25lIHByZXJlcXVpc2l0bzogJElkIgogICAgaWYgKC1ub3QgKEdldC1Db21tYW5kIHdpbmdldCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkpIHsKICAgICAgICB0aHJvdyAiUGVyIGluc3RhbGxhcmUgJElkIHNlcnZlIEFwcCBJbnN0YWxsZXIgKHdpbmdldCkgZGkgTWljcm9zb2Z0LiBJbnN0YWxsYXJsbyBlIHJpcHJvdmFyZS4iCiAgICB9CiAgICBSdW4tQ2hlY2tlZCAnd2luZ2V0JyBAKCdpbnN0YWxsJywnLS1pZCcsJElkLCctLWV4YWN0JywnLS1zb3VyY2UnLCd3aW5nZXQnLCctLWFjY2VwdC1zb3VyY2UtYWdyZWVtZW50cycsJy0tYWNjZXB0LXBhY2thZ2UtYWdyZWVtZW50cycsJy0tZGlzYWJsZS1pbnRlcmFjdGl2aXR5JykKICAgIFJlZnJlc2gtUGF0aAp9CmZ1bmN0aW9uIEZpbmQtUHl0aG9uMzEyIHsKICAgICRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAnQ29udGludWUnCiAgICAkcGF0aHMgPSBAKCIkZW52OkxPQ0FMQVBQREFUQVxQcm9ncmFtc1xQeXRob25cUHl0aG9uMzEyXHB5dGhvbi5leGUiLCAiJGVudjpQcm9ncmFtRmlsZXNcUHl0aG9uMzEyXHB5dGhvbi5leGUiLCAnQzpcUHl0aG9uMzEyXHB5dGhvbi5leGUnKQogICAgaWYgKEdldC1Db21tYW5kIHB5IC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSB7CiAgICAgICAgJHByb2JlID0gJiBweSAtMy4xMiAtYyAnaW1wb3J0IHN5czsgcHJpbnQoc3lzLmV4ZWN1dGFibGUpJyAyPiRudWxsCiAgICAgICAgaWYgKCRMQVNURVhJVENPREUgLWVxIDApIHsgJHBhdGhzID0gQCgkcHJvYmUpICsgJHBhdGhzIH0KICAgIH0KICAgIGZvcmVhY2ggKCRjYW5kaWRhdGUgaW4gJHBhdGhzKSB7CiAgICAgICAgaWYgKFRlc3QtUGF0aCAtTGl0ZXJhbFBhdGggJGNhbmRpZGF0ZSAtUGF0aFR5cGUgTGVhZikgewogICAgICAgICAgICAmICRjYW5kaWRhdGUgLWMgJ2ltcG9ydCBzeXM7IHN5cy5leGl0KDAgaWYgc3lzLnZlcnNpb25faW5mb1s6Ml0gPT0gKDMsMTIpIGFuZCBzeXMubWF4c2l6ZSA+IDIqKjMyIGVsc2UgMSknIDI+JG51bGwKICAgICAgICAgICAgaWYgKCRMQVNURVhJVENPREUgLWVxIDApIHsgcmV0dXJuICRjYW5kaWRhdGUgfQogICAgICAgIH0KICAgIH0KICAgIHJldHVybiAkbnVsbAp9CmZ1bmN0aW9uIFNob3ctSW5zdGFsbGF0aW9uQ2hlY2tsaXN0IHsKICAgICRweSA9IEZpbmQtUHl0aG9uMzEyCiAgICAkcm93cyA9IEAoCiAgICAgICAgW3BzY3VzdG9tb2JqZWN0XUB7Q29tcG9uZW50ZT0nV2luZG93cyB4NjQnOyBTdGF0bz0kKGlmKFtFbnZpcm9ubWVudF06OklzNjRCaXRPcGVyYXRpbmdTeXN0ZW0peydPSyd9ZWxzZXsnTk9OIENPTVBBVElCSUxFJ30pOyBBemlvbmU9J1dpbmRvd3MgMTAvMTEgeDY0J30sCiAgICAgICAgW3BzY3VzdG9tb2JqZWN0XUB7Q29tcG9uZW50ZT0nUHl0aG9uIDMuMTIgeDY0JzsgU3RhdG89JChpZigkcHkpeydQUkVTRU5URSd9ZWxzZXsnTUFOQ0FOVEUnfSk7IEF6aW9uZT0nSW5zdGFsbGF6aW9uZSBhdXRvbWF0aWNhIHRyYW1pdGUgd2luZ2V0J30sCiAgICAgICAgW3BzY3VzdG9tb2JqZWN0XUB7Q29tcG9uZW50ZT0nTm9kZS5qcyAvIG5wbSc7IFN0YXRvPSQoaWYoR2V0LUNvbW1hbmQgbnBtLmNtZCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSl7J1BSRVNFTlRFJ31lbHNleydNQU5DQU5URSd9KTsgQXppb25lPSdJbnN0YWxsYXppb25lIGF1dG9tYXRpY2EgdHJhbWl0ZSB3aW5nZXQnfSwKICAgICAgICBbcHNjdXN0b21vYmplY3RdQHtDb21wb25lbnRlPSd3aW5nZXQnOyBTdGF0bz0kKGlmKEdldC1Db21tYW5kIHdpbmdldCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSl7J1BSRVNFTlRFJ31lbHNleydNQU5DQU5URSd9KTsgQXppb25lPSdNaWNyb3NvZnQgQXBwIEluc3RhbGxlciwgcmljaGllc3RvIHBlciBwcmVyZXF1aXNpdGkgbWFuY2FudGknfSwKICAgICAgICBbcHNjdXN0b21vYmplY3RdQHtDb21wb25lbnRlPSdXaXJlc2hhcmsgLyB0c2hhcmsnOyBTdGF0bz0kKGlmKFRlc3QtUGF0aCAiJGVudjpQcm9ncmFtRmlsZXNcV2lyZXNoYXJrXHRzaGFyay5leGUiKXsnUFJFU0VOVEUnfWVsc2V7J01BTkNBTlRFJ30pOyBBemlvbmU9J0luc3RhbGxhemlvbmUgdHJhbWl0ZSB3aW5nZXQnfSwKICAgICAgICBbcHNjdXN0b21vYmplY3RdQHtDb21wb25lbnRlPSdObWFwJzsgU3RhdG89JChpZigoVGVzdC1QYXRoICIke2VudjpQcm9ncmFtRmlsZXMoeDg2KX1cTm1hcFxubWFwLmV4ZSIpIC1vciAoR2V0LUNvbW1hbmQgbm1hcC5leGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUpKXsnUFJFU0VOVEUnfWVsc2V7J01BTkNBTlRFJ30pOyBBemlvbmU9J0luc3RhbGxhemlvbmUgdHJhbWl0ZSB3aW5nZXQnfSwKICAgICAgICBbcHNjdXN0b21vYmplY3RdQHtDb21wb25lbnRlPSdOcGNhcCc7IFN0YXRvPSQoaWYoVGVzdC1QYXRoICIkZW52OldJTkRJUlxTeXN0ZW0zMlxOcGNhcFx3cGNhcC5kbGwiKXsnUFJFU0VOVEUnfWVsc2V7J01BTkNBTlRFJ30pOyBBemlvbmU9J1NlIG1hbmNhLCBjb21wbGV0YXJlIGlsIHNldHVwIGRyaXZlcjogaHR0cHM6Ly9ucGNhcC5jb20vI2Rvd25sb2FkJ30sCiAgICAgICAgW3BzY3VzdG9tb2JqZWN0XUB7Q29tcG9uZW50ZT0nVGFpbHNjYWxlJzsgU3RhdG89JChpZihUZXN0LVBhdGggIiRlbnY6UHJvZ3JhbUZpbGVzXFRhaWxzY2FsZVx0YWlsc2NhbGUuZXhlIil7J1BSRVNFTlRFJ31lbHNleydNQU5DQU5URSd9KTsgQXppb25lPSdJbnN0YWxsYSBzZSBtYW5jYTsgYWNjZXNzbyBhY2NvdW50IGRhIGNvbXBsZXRhcmUgcGVyIGlsIHJlbW90byd9LAogICAgICAgIFtwc2N1c3RvbW9iamVjdF1Ae0NvbXBvbmVudGU9J00zIGluc3RhbGxhdG8nOyBTdGF0bz0kKGlmKFRlc3QtUGF0aCAiJEluc3RhbGxSb290XGluc3RhbGxlZF9yZWxlYXNlLmpzb24iKXsnUFJFU0VOVEUgLSBVU0FSRSBVUERBVEUnfWVsc2V7J05VT1ZBIElOU1RBTExBWklPTkUgREEgVkVSSUZJQ0FSRSd9KTsgQXppb25lPSdOZXNzdW5hIHNvdnJhc2NyaXR0dXJhIGRpIGluc3RhbGxhemlvbmkgZXNpc3RlbnRpJ30sCiAgICAgICAgW3BzY3VzdG9tb2JqZWN0XUB7Q29tcG9uZW50ZT0nTGljZW56YSBNMyc7IFN0YXRvPSdEQSBWRVJJRklDQVJFIE5FTEwgQVBQJzsgQXppb25lPSdBdHRpdmF6aW9uZSBkb3BvIGluc3RhbGxhemlvbmUnfQogICAgKQogICAgV3JpdGUtSG9zdCAiYG5DSEVDS0xJU1QgSU5TVEFMTEFaSU9ORSBNM1BSTyIgLUZvcmVncm91bmRDb2xvciBDeWFuCiAgICAkcm93cyB8IEZvcm1hdC1UYWJsZSAtQXV0b1NpemUgLVdyYXAgfCBPdXQtSG9zdAogICAgV3JpdGUtVXRmOCAoSm9pbi1QYXRoICRXb3JrICdjaGVja2xpc3QuanNvbicpICgkcm93cyB8IENvbnZlcnRUby1Kc29uKQogICAgaWYgKCRTdGF0dXNGaWxlKSB7CiAgICAgICAgV3JpdGUtVXRmOCAkU3RhdHVzRmlsZSAoQHtjaGVja2xpc3Q9JHJvd3M7bG9nX2RpcmVjdG9yeT0kV29ya30gfCBDb252ZXJ0VG8tSnNvbiAtRGVwdGggNSkKICAgIH0KfQpmdW5jdGlvbiBWYWxpZGF0ZS1NYW5pZmVzdCgkTWFuaWZlc3QpIHsKICAgIGlmICgkTWFuaWZlc3Quc2NoZW1hIC1uZSAxIC1vciAkTWFuaWZlc3QuY2hhbm5lbCAtbmUgJ3N0YWJsZScgLW9yICRNYW5pZmVzdC5wcmVyZWxlYXNlIC1uZSAkZmFsc2UgLW9yCiAgICAgICAgJE1hbmlmZXN0LnZlcnNpb24gLW5vdG1hdGNoICdeXGQrXC5cZCtcLlxkKyQnIC1vcgogICAgICAgICRNYW5pZmVzdC5jb21taXQgLW5vdG1hdGNoICdeW2EtZkEtRjAtOV17NDB9JCcgLW9yCiAgICAgICAgJE1hbmlmZXN0LnNoYTI1NiAtbm90bWF0Y2ggJ15bYS1mQS1GMC05XXs2NH0kJyAtb3IKICAgICAgICAkTWFuaWZlc3QuemlwX25hbWUgLW5vdG1hdGNoICdeW2EtekEtWjAtOS5fLV0rXC56aXAkJyAtb3IKICAgICAgICBbbG9uZ10kTWFuaWZlc3Quc2l6ZSAtbGUgMCAtb3IgW2xvbmddJE1hbmlmZXN0LnNpemUgLWd0IDIxNDc0ODM2NDgpIHsKICAgICAgICB0aHJvdyAnTWFuaWZlc3QgdWZmaWNpYWxlIG5vbiB2YWxpZG86IGluc3RhbGxhemlvbmUgaW50ZXJyb3R0YS4nCiAgICB9CiAgICBpZiAoJE1hbmlmZXN0LnJlbGVhc2VfaWQgLW5lICgkTWFuaWZlc3QudmVyc2lvbiArICcrJyArICRNYW5pZmVzdC5jb21taXQuU3Vic3RyaW5nKDAsNykpIC1vcgogICAgICAgICRNYW5pZmVzdC5hcHByb3ZhbC5yZWxlYXNlX2lkIC1uZSAkTWFuaWZlc3QucmVsZWFzZV9pZCAtb3IKICAgICAgICAtbm90ICRNYW5pZmVzdC5hcHByb3ZhbC5hcHByb3ZlZF9ieSAtb3IgLW5vdCAkTWFuaWZlc3QuYXBwcm92YWwuYXBwcm92ZWRfYXQgLW9yCiAgICAgICAgJE1hbmlmZXN0LmFwcHJvdmFsLnNoYTI1NiAtbmUgJE1hbmlmZXN0LnNoYTI1NikgeyB0aHJvdyAnQXBwcm92YXppb25lIHJlbGVhc2Ugbm9uIGNvZXJlbnRlLicgfQp9CmZ1bmN0aW9uIEV4cGFuZC1TYWZlKFtzdHJpbmddJFppcCwgW3N0cmluZ10kRGVzdGluYXRpb24pIHsKICAgIEFkZC1UeXBlIC1Bc3NlbWJseU5hbWUgU3lzdGVtLklPLkNvbXByZXNzaW9uLkZpbGVTeXN0ZW0KICAgICRwcmVmaXggPSBbSU8uUGF0aF06OkdldEZ1bGxQYXRoKCREZXN0aW5hdGlvbikuVHJpbUVuZCgnXCcpICsgJ1wnCiAgICAkYXJjaGl2ZSA9IFtJTy5Db21wcmVzc2lvbi5aaXBGaWxlXTo6T3BlblJlYWQoJFppcCkKICAgIHRyeSB7CiAgICAgICAgJHNlZW4gPSBAe30KICAgICAgICBmb3JlYWNoICgkZW50cnkgaW4gJGFyY2hpdmUuRW50cmllcykgewogICAgICAgICAgICAkbmFtZSA9ICRlbnRyeS5GdWxsTmFtZS5SZXBsYWNlKCcvJywnXCcpCiAgICAgICAgICAgICR0YXJnZXQgPSBbSU8uUGF0aF06OkdldEZ1bGxQYXRoKChKb2luLVBhdGggJERlc3RpbmF0aW9uICRuYW1lKSkKICAgICAgICAgICAgaWYgKCRuYW1lLkNvbnRhaW5zKCc6JykgLW9yICRuYW1lLlN0YXJ0c1dpdGgoJ1wnKSAtb3IKICAgICAgICAgICAgICAgIC1ub3QgJHRhcmdldC5TdGFydHNXaXRoKCRwcmVmaXgsW1N0cmluZ0NvbXBhcmlzb25dOjpPcmRpbmFsSWdub3JlQ2FzZSkgLW9yCiAgICAgICAgICAgICAgICAkc2Vlbi5Db250YWluc0tleSgkdGFyZ2V0KSAtb3IgKCgkZW50cnkuRXh0ZXJuYWxBdHRyaWJ1dGVzIC1zaHIgMTYpIC1iYW5kIDB4RjAwMCkgLWVxIDB4QTAwMCkgewogICAgICAgICAgICAgICAgdGhyb3cgIlBlcmNvcnNvIFpJUCBub24gdmFsaWRvOiAkbmFtZSIKICAgICAgICAgICAgfQogICAgICAgICAgICAkc2VlblskdGFyZ2V0XSA9ICR0cnVlCiAgICAgICAgICAgIGlmICgkbmFtZS5FbmRzV2l0aCgnXCcpKSB7IFtJTy5EaXJlY3RvcnldOjpDcmVhdGVEaXJlY3RvcnkoJHRhcmdldCkgfCBPdXQtTnVsbDsgY29udGludWUgfQogICAgICAgICAgICBbSU8uRGlyZWN0b3J5XTo6Q3JlYXRlRGlyZWN0b3J5KFtJTy5QYXRoXTo6R2V0RGlyZWN0b3J5TmFtZSgkdGFyZ2V0KSkgfCBPdXQtTnVsbAogICAgICAgICAgICBbSU8uQ29tcHJlc3Npb24uWmlwRmlsZUV4dGVuc2lvbnNdOjpFeHRyYWN0VG9GaWxlKCRlbnRyeSwgJHRhcmdldCwgJGZhbHNlKQogICAgICAgIH0KICAgIH0gZmluYWxseSB7ICRhcmNoaXZlLkRpc3Bvc2UoKSB9Cn0KCnRyeSB7CiAgICBpZiAoLW5vdCBbRW52aXJvbm1lbnRdOjpJczY0Qml0T3BlcmF0aW5nU3lzdGVtKSB7IHRocm93ICdXaW5kb3dzIHg2NCByaWNoaWVzdG8uJyB9CiAgICBpZiAoLW5vdCAkQ2hlY2tPbmx5IC1hbmQgLW5vdCAkQ2hlY2tsaXN0T25seSkgewogICAgICAgICRwcmluY2lwYWwgPSBOZXctT2JqZWN0IFNlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsKFtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lkZW50aXR5XTo6R2V0Q3VycmVudCgpKQogICAgICAgIGlmICgtbm90ICRwcmluY2lwYWwuSXNJblJvbGUoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzQnVpbHRJblJvbGVdOjpBZG1pbmlzdHJhdG9yKSkgewogICAgICAgICAgICB0aHJvdyAnQXByaXJlIFBvd2VyU2hlbGwgY29tZSBhbW1pbmlzdHJhdG9yZSBlIHJpbGFuY2lhcmUgbG8gc3Rlc3NvIGNvbWFuZG8uJwogICAgICAgIH0KICAgICAgICBpZiAoJENvbmZpZ0ZpbGUpIHsKICAgICAgICAgICAgJENvbmZpZ0ZpbGUgPSAoUmVzb2x2ZS1QYXRoIC1MaXRlcmFsUGF0aCAkQ29uZmlnRmlsZSkuUGF0aAogICAgICAgICAgICAkUHJpdmF0ZUNvbmZpZyA9IFtJTy5GaWxlXTo6UmVhZEFsbFRleHQoJENvbmZpZ0ZpbGUpCiAgICAgICAgfQogICAgICAgICMgTWFpIGNhbmNlbGxhcmUgbyByZXNldHRhcmUgdW4gTTMgZXNpc3RlbnRlLCBuZXBwdXJlIGRvcG8gdW4gZXJyb3JlLgogICAgICAgIGlmICgoVGVzdC1QYXRoICRJbnN0YWxsUm9vdCkgLWFuZCBAKEdldC1DaGlsZEl0ZW0gLUxpdGVyYWxQYXRoICRJbnN0YWxsUm9vdCAtRm9yY2UpLkNvdW50IC1ndCAwKSB7CiAgICAgICAgICAgICRtYWNoaW5lRmlsZXMgPSBAKCdiYWNrZW5kXC5lbnYnLCdtMy1weXRob24tcGF0aC50eHQnLCdpbnN0YWxsZWRfcmVsZWFzZS5qc29uJywnbTMtdXBkYXRlLWxvY2FsLmpzb24nLCcudmVudicsJy5ydW50aW1lJywnZnJvbnRlbmRcbm9kZV9tb2R1bGVzJywnc2Vzc2lvbnMnLCdyZXBvcnRzJywnbG9ncycsJ2xpY2Vuc2VzLmpzb24nLCdsaWNlbnNlLmpzb24nKQogICAgICAgICAgICAkY29uZmlndXJlZCA9IEAoJG1hY2hpbmVGaWxlcyB8IFdoZXJlLU9iamVjdCB7IFRlc3QtUGF0aCAoSm9pbi1QYXRoICRJbnN0YWxsUm9vdCAkXykgfSkuQ291bnQgLWd0IDAKICAgICAgICAgICAgaWYgKCRjb25maWd1cmVkIC1vciAtbm90IChUZXN0LVBhdGggIiRJbnN0YWxsUm9vdFwuZ2l0IikpIHsKICAgICAgICAgICAgICAgIHRocm93ICdDOlxNRUZGIGNvbnRpZW5lIGdpYSBmaWxlIGRpIGluc3RhbGxhemlvbmUuIFBlciBNMyBpbnN0YWxsYXRvIHVzYXJlIFVwZGF0ZS4gSSBkYXRpIGVzaXN0ZW50aSBub24gdmVuZ29ubyBzb3ZyYXNjcml0dGkuJwogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQogICAgTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9yeSAtUGF0aCAkV29yayB8IE91dC1OdWxsCiAgICBTdGFydC1UcmFuc2NyaXB0IC1QYXRoIChKb2luLVBhdGggJFdvcmsgJ2luc3RhbGxhemlvbmUubG9nJykgfCBPdXQtTnVsbAogICAgU2hvdy1JbnN0YWxsYXRpb25DaGVja2xpc3QKICAgIGlmICgkQ2hlY2tsaXN0T25seSkgewogICAgICAgIFdyaXRlLUhvc3QgIlNvbG8gY29udHJvbGxvLCBuZXNzdW5hIGluc3RhbGxhemlvbmUuIENoZWNrbGlzdCBzYWx2YXRhIGluICRXb3JrIgogICAgICAgIFN0b3AtVHJhbnNjcmlwdCB8IE91dC1OdWxsCiAgICAgICAgZXhpdCAwCiAgICB9CiAgICBXcml0ZS1Ib3N0ICdTY2FyaWNvIGUgdmVyaWZpY28gdWx0aW1hIHZlcnNpb25lIHVmZmljaWFsZSBNM1BSTy4uLicKICAgICRNYW5pZmVzdCA9IEludm9rZS1SZXN0TWV0aG9kIC1VcmkgIiRGZWVkL20zcHJvLXN0YWJsZS1tYW5pZmVzdC5qc29uIiAtVGltZW91dFNlYyA2MAogICAgVmFsaWRhdGUtTWFuaWZlc3QgJE1hbmlmZXN0CiAgICBpZiAoJE1hbmlmZXN0LnJlcXVpcmVzLm9zIC1hbmQgJE1hbmlmZXN0LnJlcXVpcmVzLm9zIC1uZSAnd2luZG93cycpIHsgdGhyb3cgJ1JlbGVhc2Ugbm9uIGRlc3RpbmF0YSBhIFdpbmRvd3MuJyB9CiAgICBpZiAoJE1hbmlmZXN0LnJlcXVpcmVzLnB5dGhvbl9taW5pbXVtIC1hbmQgW3ZlcnNpb25dJE1hbmlmZXN0LnJlcXVpcmVzLnB5dGhvbl9taW5pbXVtIC1ndCBbdmVyc2lvbl0nMy4xMi4wJykgewogICAgICAgIHRocm93ICdMYSBudW92YSByZWxlYXNlIHJpY2hpZWRlIHVuIHJ1bnRpbWUgc3VwZXJpb3JlOiBhZ2dpb3JuYXJlIHF1ZXN0byBpbnN0YWxsZXIgcHJpbWEgZGkgcHJvc2VndWlyZS4nCiAgICB9CiAgICAkWmlwID0gSm9pbi1QYXRoICRXb3JrICRNYW5pZmVzdC56aXBfbmFtZQogICAgIyBJbCBwYWNjaGV0dG8gZGV2ZSBwcm92ZW5pcmUgZGFsbG8gc3Rlc3NvIGZlZWQgcHViYmxpY28gY29uZmlndXJhdG8uCiAgICBJbnZva2UtV2ViUmVxdWVzdCAtVXNlQmFzaWNQYXJzaW5nIC1VcmkgIiRGZWVkLyQoJE1hbmlmZXN0LnppcF9uYW1lKSIgLU91dEZpbGUgJFppcCAtVGltZW91dFNlYyA2MDAKICAgIGlmICgoR2V0LUl0ZW0gJFppcCkuTGVuZ3RoIC1uZSBbbG9uZ10kTWFuaWZlc3Quc2l6ZSAtb3IgKEdldC1GaWxlSGFzaCAkWmlwIC1BbGdvcml0aG0gU0hBMjU2KS5IYXNoIC1uZSAkTWFuaWZlc3Quc2hhMjU2KSB7CiAgICAgICAgdGhyb3cgJ0RpbWVuc2lvbmUgbyBTSEEyNTYgZGVsIHBhY2NoZXR0byBub24gY29ycmlzcG9uZG9ubyBhbGxhIHJlbGVhc2UgYXBwcm92YXRhLicKICAgIH0KICAgICRTdGFnZSA9IEpvaW4tUGF0aCAkV29yayAncmVsZWFzZScKICAgIEV4cGFuZC1TYWZlICRaaXAgJFN0YWdlCiAgICBmb3JlYWNoICgkZmlsZSBpbiBAKCdWRVJTSU9OJywnYmFja2VuZC9zZXJ2ZXIucHknLCdmcm9udGVuZC9idWlsZC9pbmRleC5odG1sJywnbTNfbGF1bmNoZXIucHknLCdtM19ydW50aW1lLnB5JywnbTNfdXBkYXRlci5weScsJ0FWVklBLU0zUFJPLnZicycpKSB7CiAgICAgICAgaWYgKC1ub3QgKFRlc3QtUGF0aCAoSm9pbi1QYXRoICRTdGFnZSAkZmlsZSkgLVBhdGhUeXBlIExlYWYpKSB7IHRocm93ICJQYWNjaGV0dG8gaW5jb21wbGV0bzogbWFuY2EgJGZpbGUiIH0KICAgIH0KICAgIGlmICgoR2V0LUNvbnRlbnQgKEpvaW4tUGF0aCAkU3RhZ2UgJ1ZFUlNJT04nKSAtUmF3KS5UcmltKCkgLW5lICRNYW5pZmVzdC52ZXJzaW9uKSB7IHRocm93ICdWRVJTSU9OIG5vbiBjb2VyZW50ZSBjb24gaWwgbWFuaWZlc3QuJyB9CiAgICBXcml0ZS1Ib3N0ICJWZXJpZmljYXRhIHJlbGVhc2UgdWZmaWNpYWxlICQoJE1hbmlmZXN0LnZlcnNpb24pLCBTSEEyNTYgY29ycmV0dG8uIgogICAgaWYgKCRDaGVja09ubHkpIHsKICAgICAgICBXcml0ZS1Ib3N0ICJWZXJpZmljYSBjb21wbGV0YXRhLCBuZXNzdW4gc2Vydml6aW8gbyBwcm9ncmFtbWEgaW5zdGFsbGF0by4gRmlsZTogJFdvcmsiCiAgICAgICAgU3RvcC1UcmFuc2NyaXB0IHwgT3V0LU51bGwKICAgICAgICBleGl0IDAKICAgIH0KICAgIGlmIChHZXQtTmV0VENQQ29ubmVjdGlvbiAtU3RhdGUgTGlzdGVuIC1Mb2NhbFBvcnQgMzAwMCw1NTU2LDgwMDEgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUpIHsKICAgICAgICB0aHJvdyAnVW5hIHBvcnRhIE0zIGUgZ2lhIG9jY3VwYXRhLiBOZXNzdW4gcHJvY2Vzc28gZSBzdGF0byBhcnJlc3RhdG86IGNoaXVkZXJlIGwgYXBwbGljYXppb25lIGludGVyZXNzYXRhIHByaW1hIGRpIGluc3RhbGxhcmUuJwogICAgfQogICAgJFB5dGhvbkJhc2UgPSBGaW5kLVB5dGhvbjMxMgogICAgaWYgKC1ub3QgJFB5dGhvbkJhc2UpIHsgSW5zdGFsbC1XaW5nZXQgJ1B5dGhvbi5QeXRob24uMy4xMic7ICRQeXRob25CYXNlID0gRmluZC1QeXRob24zMTIgfQogICAgaWYgKC1ub3QgJFB5dGhvbkJhc2UpIHsgdGhyb3cgJ1B5dGhvbiAzLjEyIHg2NCBub24gdHJvdmF0byBkb3BvIGluc3RhbGxhemlvbmUuJyB9CiAgICBpZiAoLW5vdCAoR2V0LUNvbW1hbmQgbnBtLmNtZCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkpIHsgSW5zdGFsbC1XaW5nZXQgJ09wZW5KUy5Ob2RlSlMuTFRTJyB9CiAgICBpZiAoLW5vdCAoR2V0LUNvbW1hbmQgbnBtLmNtZCAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkpIHsgdGhyb3cgJ05vZGUuanMvbnBtIG5vbiBkaXNwb25pYmlsZS4nIH0KICAgIGlmICgoVGVzdC1QYXRoICRJbnN0YWxsUm9vdCkgLWFuZCBAKEdldC1DaGlsZEl0ZW0gLUxpdGVyYWxQYXRoICRJbnN0YWxsUm9vdCAtRm9yY2UpLkNvdW50IC1ndCAwKSB7CiAgICAgICAgIyBEZXN0aW5hemlvbmUgZmlzc2EgdmVyaWZpY2F0YSwgZnVvcmkgZGFsbGEgY2FydGVsbGEgZGEgYXJjaGl2aWFyZTsgbmVzc3VuYSBlbGltaW5hemlvbmUuCiAgICAgICAgJEJhY2t1cCA9ICdDOlxNRUZGLXNvcmdlbnRpLScgKyBbZ3VpZF06Ok5ld0d1aWQoKS5Ub1N0cmluZygnTicpCiAgICAgICAgaWYgKFtJTy5QYXRoXTo6R2V0RnVsbFBhdGgoJEluc3RhbGxSb290KSAtbmUgJ0M6XE1FRkYnIC1vciAtbm90ICRCYWNrdXAuU3RhcnRzV2l0aCgnQzpcTUVGRi1zb3JnZW50aS0nKSkgeyB0aHJvdyAnUGVyY29yc28gYXJjaGl2aW8gbm9uIHZhbGlkby4nIH0KICAgICAgICBTZXQtTG9jYXRpb24gJFdvcmsKICAgICAgICBNb3ZlLUl0ZW0gLUxpdGVyYWxQYXRoICRJbnN0YWxsUm9vdCAtRGVzdGluYXRpb24gJEJhY2t1cAogICAgICAgIFdyaXRlLUhvc3QgIkNsb25lIG9yaWdpbmFsZSBjb25zZXJ2YXRvIGluICRCYWNrdXAiCiAgICB9CiAgICBOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1QYXRoICRJbnN0YWxsUm9vdCAtRm9yY2UgfCBPdXQtTnVsbAogICAgR2V0LUNoaWxkSXRlbSAtTGl0ZXJhbFBhdGggJFN0YWdlIC1Gb3JjZSB8IENvcHktSXRlbSAtRGVzdGluYXRpb24gJEluc3RhbGxSb290IC1SZWN1cnNlCiAgICAjIENvbnNlcnZhIHF1ZXN0byBib290c3RyYXAgY29ycmV0dG86IGxvIFpJUCBwdW8gY29udGVuZXJlIHVuIGluc3RhbGxlciBwcmVjZWRlbnRlLgogICAgV3JpdGUtVXRmOCAoSm9pbi1QYXRoICRJbnN0YWxsUm9vdCAnSU5TVEFMTEEtTUVGRi5wczEnKSAkQm9vdHN0cmFwU291cmNlCiAgICBXcml0ZS1Ib3N0ICdQcmVwYXJvIGFtYmllbnRlIFB5dGhvbiBkZWRpY2F0byBhIE0zLi4uJwogICAgUnVuLUNoZWNrZWQgJFB5dGhvbkJhc2UgQCgnLW0nLCd2ZW52JywiJEluc3RhbGxSb290XC52ZW52IikKICAgICRQeXRob24gPSAiJEluc3RhbGxSb290XC52ZW52XFNjcmlwdHNccHl0aG9uLmV4ZSIKICAgIFJ1bi1DaGVja2VkICRQeXRob24gQCgnLW0nLCdwaXAnLCdpbnN0YWxsJywnLS11cGdyYWRlJywncGlwJykKICAgICMgVW4gdW5pY28gcmVzb2x2ZXI7IG5vbiB1c2FyZSByZXF1aXJlbWVudHMudHh0IGNsb3VkIChjb250aWVuZSBwaW4gaW5jb21wYXRpYmlsaSBXaW5kb3dzKS4KICAgICRQYWNrYWdlcyA9IEAoJ2Zhc3RhcGk9PTAuMTEwLjEnLCd1dmljb3JuPT0wLjM0LjAnLCdtb3Rvcj09My43LjAnLCdweW1vbmdvPT00LjExLjEnLCdweWRhbnRpY1tlbWFpbF09PTIuMTEuNScsJ3B5ZGFudGljLXNldHRpbmdzPT0yLjkuMScsJ3B5dGhvbi1kb3RlbnYnLCdQeUpXVCcsJ3B5dGhvbi1qb3NlW2NyeXB0b2dyYXBoeV0nLCdwYXNzbGliJywnYmNyeXB0PT00LjEuMycsJ3B5dGhvbi1tdWx0aXBhcnQnLCdhaW9maWxlcycsJ2Fpb2h0dHAnLCdodHRweD49MC4yOCw8MC4yOScsJ3JlcXVlc3RzJywncXJjb2RlJywncmVwb3J0bGFiPT00LjQuNCcsJ1BpbGxvdz09MTEuMy4wJywnUHlNdVBERicsJ3BzdXRpbD09NS45LjgnLCdzY2FweT09Mi42LjEnLCdudW1weT09Mi4yLjYnLCdwYW5kYXM9PTIuMi4zJywncHl0aG9uLW5tYXAnLCd0d2lsaW8nLCdvcGVuYWk9PTEuOTkuOScsJ2xpdGVsbG09PTEuNzguMCcsJ2dvb2dsZS1nZW5haT09MS40NC4wJywncHJvdG9idWY9PTUuMjkuNScsJ2JvdG8zJywnUHlZQU1MJywncHl0aG9uLWRhdGV1dGlsJywnd2luZG93cy1jdXJzZXMnLCdweXRob24tZXZ0eCcsJ3B5dGhvbi1yZWdpc3RyeScsJ21pdG1wcm94eT09MTEuMC4yJywnbXZ0PT0yLjYuMCcsJ2VtZXJnZW50aW50ZWdyYXRpb25zPT0wLjEuMCcsJ2h0dHBzOi8vZ2l0aHViLmNvbS9FQy1ESUdJVC1DU0lSQy9zeXNkaWFnbm9zZS9hcmNoaXZlLzExODBiY2I4YWM5NTRkYjY0OTgwMDM4Y2U3MTRkYjJkYWQ4YTE4MzIuemlwJykKICAgIFJ1bi1DaGVja2VkICRQeXRob24gKEAoJy1tJywncGlwJywnaW5zdGFsbCcsJy0tZXh0cmEtaW5kZXgtdXJsJywnaHR0cHM6Ly9kMzNzeTVpOGJuZHV3ZS5jbG91ZGZyb250Lm5ldC9zaW1wbGUvJykgKyAkUGFja2FnZXMpCiAgICBSdW4tQ2hlY2tlZCAkUHl0aG9uIEAoJy1tJywncGlwJywnY2hlY2snKQogICAgUnVuLUNoZWNrZWQgJFB5dGhvbiBAKCctYycsJ2ltcG9ydCB1dmljb3JuLCBmYXN0YXBpLCBtb3RvciwgcHltb25nbywgcmVwb3J0bGFiLCBzY2FweSwgcHN1dGlsLCBzeXNkaWFnbm9zZSwgbWl0bXByb3h5LCBtdnQsIGZpdHosIGp3dDsgZnJvbSBlbWVyZ2VudGludGVncmF0aW9ucy5sbG0uY2hhdCBpbXBvcnQgTGxtQ2hhdCcpCiAgICBXcml0ZS1VdGY4ICIkSW5zdGFsbFJvb3RcbTMtcHl0aG9uLXBhdGgudHh0IiAoJFB5dGhvbiArICJgbiIpCiAgICAjIFNvbG8gaWwgc2VydmVyIHN0YXRpY286IGxhIFVJIGUgZ2lhIGNvbXBpbGF0YSBlIHZlcmlmaWNhdGEgbmVsbG8gWklQIHVmZmljaWFsZS4KICAgICRTZXJ2ZSA9IEpvaW4tUGF0aCAkV29yayAnc3RhdGljLXNlcnZlcicKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLVBhdGggJFNlcnZlIHwgT3V0LU51bGwKICAgIFJ1bi1DaGVja2VkICducG0uY21kJyBAKCdpbnN0YWxsJywnLS1wcmVmaXgnLCRTZXJ2ZSwnLS1uby1hdWRpdCcsJy0tbm8tZnVuZCcsJ3NlcnZlQDE0LjIuNCcpCiAgICBDb3B5LUl0ZW0gLUxpdGVyYWxQYXRoICIkU2VydmVcbm9kZV9tb2R1bGVzIiAtRGVzdGluYXRpb24gIiRJbnN0YWxsUm9vdFxmcm9udGVuZFxub2RlX21vZHVsZXMiIC1SZWN1cnNlCiAgICBXcml0ZS1VdGY4ICIkSW5zdGFsbFJvb3RcbTMtdXBkYXRlLWxvY2FsLmpzb24iIChAe2NoYW5uZWw9J3N0YWJsZSc7ZmVlZF9iYXNlX3VybD0kRmVlZDtpbnN0YWxsX2VuYWJsZWQ9JHRydWV9IHwgQ29udmVydFRvLUpzb24pCiAgICBpZiAoJENvbmZpZ0ZpbGUpIHsgV3JpdGUtVXRmOCAiJEluc3RhbGxSb290XGJhY2tlbmRcLmVudiIgJFByaXZhdGVDb25maWcgfQogICAgZWxzZSB7CiAgICAgICAgJGJ5dGVzID0gTmV3LU9iamVjdCBieXRlW10gNDgKICAgICAgICAkcm5nID0gW1NlY3VyaXR5LkNyeXB0b2dyYXBoeS5SYW5kb21OdW1iZXJHZW5lcmF0b3JdOjpDcmVhdGUoKQogICAgICAgIHRyeSB7ICRybmcuR2V0Qnl0ZXMoJGJ5dGVzKSB9IGZpbmFsbHkgeyAkcm5nLkRpc3Bvc2UoKSB9CiAgICAgICAgJHNlY3JldCA9IFtDb252ZXJ0XTo6VG9CYXNlNjRTdHJpbmcoJGJ5dGVzKQogICAgICAgIFdyaXRlLVV0ZjggIiRJbnN0YWxsUm9vdFxiYWNrZW5kXC5lbnYiICJKV1RfU0VDUkVUPSRzZWNyZXRgbk0zX0FETUlOX1VTRVI9YWRtaW5gbk0zX0FETUlOX1BBU1M9JHNlY3JldGBuQVBQX1VSTD1odHRwczovL3BjLW5ldHdvcmstc2Nhbi5lbWVyZ2VudC5ob3N0YG5QQVlQQUxfRU5BQkxFRD1mYWxzZWBuQ09SU19PUklHSU5TPWh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCxodHRwOi8vMTI3LjAuMC4xOjMwMDBgbiIKICAgIH0KICAgICROb3RlcyA9IE5ldy1PYmplY3QgJ1N5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3Rbc3RyaW5nXScKICAgICMgTW9kdWxvIGxlZ2FjeTogbmVzc3VuYSBjb21waWxhemlvbmUgQysrIGF1dG9tYXRpY2Egc3VsIFBDIGRlbCBjbGllbnRlLgogICAgdHJ5IHsgUnVuLUNoZWNrZWQgJFB5dGhvbiBAKCctbScsJ3BpcCcsJ2luc3RhbGwnLCctLW9ubHktYmluYXJ5PTphbGw6JywnbmV0aWZhY2VzPT0wLjExLjAnKSB9CiAgICBjYXRjaCB7ICROb3Rlcy5BZGQoJ25ldGlmYWNlczogd2hlZWwgY29tcGF0aWJpbGUgbm9uIGRpc3BvbmliaWxlOyBlbnVtZXJhemlvbmUgcmV0ZSB0cmFtaXRlIHBzdXRpbC4gSWwgY29udHJvbGxvIHN0cnVtZW50aSBQUk8gcHVvIHNlZ25hbGFybG8gY29tZSBtYW5jYW50ZS4nKSB9CiAgICBpZiAoLW5vdCAkU2tpcEV4dGVybmFsVG9vbHMpIHsKICAgICAgICBmb3JlYWNoICgkdG9vbCBpbiBAKAogICAgICAgICAgICBAe0lkPSdXaXJlc2hhcmtGb3VuZGF0aW9uLldpcmVzaGFyayc7UGF0aD0iJGVudjpQcm9ncmFtRmlsZXNcV2lyZXNoYXJrXHRzaGFyay5leGUifSwKICAgICAgICAgICAgQHtJZD0nSW5zZWN1cmUuTm1hcCc7UGF0aD0iJHtlbnY6UHJvZ3JhbUZpbGVzKHg4Nil9XE5tYXBcbm1hcC5leGUifSwKICAgICAgICAgICAgQHtJZD0nVGFpbHNjYWxlLlRhaWxzY2FsZSc7UGF0aD0iJGVudjpQcm9ncmFtRmlsZXNcVGFpbHNjYWxlXHRhaWxzY2FsZS5leGUifQogICAgICAgICkpIHsKICAgICAgICAgICAgaWYgKC1ub3QgKFRlc3QtUGF0aCAkdG9vbC5QYXRoKSkgewogICAgICAgICAgICAgICAgdHJ5IHsgSW5zdGFsbC1XaW5nZXQgJHRvb2wuSWQ7IGlmICgtbm90IChUZXN0LVBhdGggJHRvb2wuUGF0aCkpIHsgdGhyb3cgJ0VzZWd1aWJpbGUgbm9uIHRyb3ZhdG8gZG9wbyBzZXR1cC4nIH0gfQogICAgICAgICAgICAgICAgY2F0Y2ggeyAkTm90ZXMuQWRkKCIkKCR0b29sLklkKTogZGEgY29tcGxldGFyZSAoJCgkXy5FeGNlcHRpb24uTWVzc2FnZSkpIikgfQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfSBlbHNlIHsgJE5vdGVzLkFkZCgnSW5zdGFsbGF6aW9uZSBzdHJ1bWVudGkgZGkgcmV0ZSBzYWx0YXRhIHN1IHJpY2hpZXN0YS4nKSB9CiAgICBpZiAoLW5vdCAoVGVzdC1QYXRoICIkZW52OldJTkRJUlxTeXN0ZW0zMlxOcGNhcFx3cGNhcC5kbGwiKSkgeyAkTm90ZXMuQWRkKCdOcGNhcDogY29tcGxldGFyZSBpbCBkcml2ZXIgZGkgY2F0dHVyYSBkYSBodHRwczovL25wY2FwLmNvbS8jZG93bmxvYWQgcHJpbWEgZGVsbGUgc2NhbnNpb25pIHRyYWZmaWNvLicpIH0KICAgICRzaCA9IE5ldy1PYmplY3QgLUNvbU9iamVjdCBXU2NyaXB0LlNoZWxsCiAgICAkbGluayA9ICRzaC5DcmVhdGVTaG9ydGN1dCgoSm9pbi1QYXRoIChbRW52aXJvbm1lbnRdOjpHZXRGb2xkZXJQYXRoKCdDb21tb25EZXNrdG9wRGlyZWN0b3J5JykpICdNM1BSTy5sbmsnKSkKICAgICRsaW5rLlRhcmdldFBhdGggPSAiJGVudjpXSU5ESVJcU3lzdGVtMzJcd3NjcmlwdC5leGUiCiAgICAkbGluay5Bcmd1bWVudHMgPSAnIkM6XE1FRkZcQVZWSUEtTTNQUk8udmJzIicKICAgICRsaW5rLldvcmtpbmdEaXJlY3RvcnkgPSAkSW5zdGFsbFJvb3QKICAgICRsaW5rLlNhdmUoKQogICAgIyBBdXRvc3RhcnQgc2lsZW56aW9zbyBwZXIgbCd1dGVudGUgY29ycmVudGUsIHNlbnphIHJpbXVvdmVyZSBhbHRyaSBzZXJ2aXppLgogICAgJHZicyA9IEAnClNldCBzaD1DcmVhdGVPYmplY3QoIldTY3JpcHQuU2hlbGwiKQpzaC5DdXJyZW50RGlyZWN0b3J5PSJDOlxNRUZGIgpzaC5SdW4gQ2hyKDM0KSAmICJDOlxNRUZGXC52ZW52XFNjcmlwdHNccHl0aG9uLmV4ZSIgJiBDaHIoMzQpICYgIiAiICYgQ2hyKDM0KSAmICJDOlxNRUZGXG0zX2xhdW5jaGVyLnB5IiAmIENocigzNCkgJiAiIC0tbW9kZSBiYWNrZ3JvdW5kIiwgMCwgRmFsc2UKJ0AKICAgIFdyaXRlLVV0ZjggIiRJbnN0YWxsUm9vdFxNMy1TVEFSVC1CQUNLR1JPVU5ELnZicyIgJHZicwogICAgJHN0YXJ0dXAgPSAkc2guQ3JlYXRlU2hvcnRjdXQoKEpvaW4tUGF0aCAoW0Vudmlyb25tZW50XTo6R2V0Rm9sZGVyUGF0aCgnU3RhcnR1cCcpKSAnTTNQUk8tQmFja2dyb3VuZC5sbmsnKSkKICAgICRzdGFydHVwLlRhcmdldFBhdGggPSAiJGVudjpXSU5ESVJcU3lzdGVtMzJcd3NjcmlwdC5leGUiCiAgICAkc3RhcnR1cC5Bcmd1bWVudHMgPSAnIkM6XE1FRkZcTTMtU1RBUlQtQkFDS0dST1VORC52YnMiJwogICAgJHN0YXJ0dXAuV29ya2luZ0RpcmVjdG9yeSA9ICRJbnN0YWxsUm9vdAogICAgJHN0YXJ0dXAuU2F2ZSgpCiAgICBXcml0ZS1VdGY4ICIkSW5zdGFsbFJvb3RcaW5zdGFsbGVkX3JlbGVhc2UuanNvbiIgKEB7dmVyc2lvbj0kTWFuaWZlc3QudmVyc2lvbjtyZWxlYXNlX2lkPSRNYW5pZmVzdC5yZWxlYXNlX2lkO2NvbW1pdD0kTWFuaWZlc3QuY29tbWl0O3NoYTI1Nj0kTWFuaWZlc3Quc2hhMjU2O2NoYW5uZWw9J3N0YWJsZSc7aW5zdGFsbGVkX2F0PVtEYXRlVGltZV06OlV0Y05vdy5Ub1N0cmluZygnbycpfSB8IENvbnZlcnRUby1Kc29uKQogICAgU3RhcnQtUHJvY2VzcyAtRmlsZVBhdGggJFB5dGhvbiAtQXJndW1lbnRMaXN0ICciQzpcTUVGRlxtM19sYXVuY2hlci5weSIgLS1tb2RlIGFwcCcgLVdvcmtpbmdEaXJlY3RvcnkgJEluc3RhbGxSb290IC1XaW5kb3dTdHlsZSBIaWRkZW4KICAgICRSZWFkeSA9ICRmYWxzZQogICAgZm9yICgkYXR0ZW1wdD0wOyAkYXR0ZW1wdCAtbHQgNDU7ICRhdHRlbXB0KyspIHsKICAgICAgICAmICRQeXRob24gIiRJbnN0YWxsUm9vdFxtM19sYXVuY2hlci5weSIgLS1tb2RlIGNoZWNrICo+IChKb2luLVBhdGggJFdvcmsgJ3NlcnZpemkubG9nJykKICAgICAgICBpZiAoJExBU1RFWElUQ09ERSAtZXEgMCkgeyAkUmVhZHkgPSAkdHJ1ZTsgYnJlYWsgfQogICAgICAgIFN0YXJ0LVNsZWVwIC1TZWNvbmRzIDIKICAgIH0KICAgIGlmICgtbm90ICRSZWFkeSkgeyB0aHJvdyAiRmlsZSBpbnN0YWxsYXRpLCBzZXJ2aXppIG5vbiB0dXR0aSBwcm9udGkuIENvbnN1bHRhcmUgJFdvcmsgZSBDOlxNRUZGXGxvZ3MuIiB9CiAgICAkTm90ZXMuQWRkKCdBdHRpdmFyZSBsYSBsaWNlbnphIGluIE0zIGUgY29tcGxldGFyZSBhY2Nlc3NvIFRhaWxzY2FsZSBwZXIgaWwgcmVtb3RvLicpCiAgICBpZiAoLW5vdCAkQ29uZmlnRmlsZSkgeyAkTm90ZXMuQWRkKCdDb25maWd1cmF6aW9uZSBwcml2YXRhIG5vbiBpbXBvcnRhdGE6IGxlIGludGVncmF6aW9uaSBjaGUgcmljaGllZG9ubyBjcmVkZW56aWFsaSBkZXZvbm8gZXNzZXJlIGNvbmZpZ3VyYXRlIGRhbCB0ZWNuaWNvLicpIH0KICAgIFdyaXRlLVV0ZjggIiRJbnN0YWxsUm9vdFxFU0lUTy1JTlNUQUxMQVpJT05FLnR4dCIgKCROb3RlcyAtam9pbiAiYHJgbiIpCiAgICBTaG93LUluc3RhbGxhdGlvbkNoZWNrbGlzdAogICAgQ29weS1JdGVtIC1MaXRlcmFsUGF0aCAoSm9pbi1QYXRoICRXb3JrICdjaGVja2xpc3QuanNvbicpIC1EZXN0aW5hdGlvbiAiJEluc3RhbGxSb290XENIRUNLTElTVC1JTlNUQUxMQVpJT05FLmpzb24iIC1Gb3JjZQogICAgV3JpdGUtSG9zdCAiTTNQUk8gJCgkTWFuaWZlc3QudmVyc2lvbikgYXZ2aWF0by4gQWdnaW9ybmFtZW50aSBzdWNjZXNzaXZpIGRhbCBjYW5hbGUgdWZmaWNpYWxlLiIKICAgICROb3RlcyB8IEZvckVhY2gtT2JqZWN0IHsgV3JpdGUtSG9zdCAkXyAtRm9yZWdyb3VuZENvbG9yIFllbGxvdyB9CiAgICBTdG9wLVRyYW5zY3JpcHQgfCBPdXQtTnVsbAogICAgZXhpdCAwCn0gY2F0Y2ggewogICAgV3JpdGUtSG9zdCAiSU5TVEFMTEFaSU9ORSBOT04gQ09NUExFVEFUQTogJCgkXy5FeGNlcHRpb24uTWVzc2FnZSkiIC1Gb3JlZ3JvdW5kQ29sb3IgUmVkCiAgICBXcml0ZS1Ib3N0ICJMb2cgZSBmaWxlIGRpYWdub3N0aWNpOiAkV29yay4gTmVzc3VuYSBjYXJ0ZWxsYSBlc2lzdGVudGUgdmllbmUgZWxpbWluYXRhLiIKICAgIHRyeSB7IFN0b3AtVHJhbnNjcmlwdCB8IE91dC1OdWxsIH0gY2F0Y2gge30KICAgIGV4aXQgMQp9DQo='
$engineHash = 'ab9b37fe9913b73b9e2a156b9ba06284441b5fcab5ac43afee7f3ce9862515a1'
$jobRoot = Join-Path $env:TEMP ('M3PRO-Setup-GUI-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $jobRoot | Out-Null
$engine = Join-Path $jobRoot 'INSTALLA-MEFF.ps1'
[IO.File]::WriteAllBytes($engine, [Convert]::FromBase64String($engineBase64))
if ((Get-FileHash $engine -Algorithm SHA256).Hash -ne $engineHash) { throw 'Il motore di installazione non supera il controllo integrita.' }
$script:worker = $null
$script:mode = ''
$script:lastLog = ''
$script:sequence = 0
$script:machinePresent = $false
$script:readyForInstall = $false
$script:stdout = ''
$script:stderr = ''
$statusFile = Join-Path $jobRoot 'checklist.json'
$dark=[Drawing.ColorTranslator]::FromHtml('#102333')
$panelColor=[Drawing.ColorTranslator]::FromHtml('#183449')
$teal=[Drawing.ColorTranslator]::FromHtml('#20CEC5')
$muted=[Drawing.ColorTranslator]::FromHtml('#B9CDD9')
$form = New-Object Windows.Forms.Form
$form.Text='M3PRO | Installazione prodotto'
$form.ClientSize=New-Object Drawing.Size(940,720)
$form.StartPosition='CenterScreen'
$form.FormBorderStyle='FixedDialog'
$form.MaximizeBox=$false
$form.BackColor=$dark
$form.ForeColor=[Drawing.Color]::White
$form.Font=New-Object Drawing.Font('Segoe UI',10)
$brand=New-Object Windows.Forms.Label
$brand.Text='MEFF  M3 PRO'
$brand.Font=New-Object Drawing.Font('Segoe UI',25,[Drawing.FontStyle]::Bold)
$brand.ForeColor=$teal
$brand.SetBounds(28,20,650,48)
$form.Controls.Add($brand)
$subtitle=New-Object Windows.Forms.Label
$subtitle.Text='SETUP WINDOWS  |  VERSIONE UFFICIALE'
$subtitle.ForeColor=$muted
$subtitle.Font=New-Object Drawing.Font('Segoe UI',10,[Drawing.FontStyle]::Bold)
$subtitle.SetBounds(32,74,850,26)
$form.Controls.Add($subtitle)
$stage=New-Object Windows.Forms.Label
$stage.Text='Preparazione della checklist del PC...'
$stage.Font=New-Object Drawing.Font('Segoe UI',12,[Drawing.FontStyle]::Bold)
$stage.SetBounds(32,113,870,32)
$form.Controls.Add($stage)
$list=New-Object Windows.Forms.ListView
$list.SetBounds(32,153,876,265)
$list.View='Details'; $list.FullRowSelect=$true; $list.GridLines=$false
$list.BackColor=$panelColor; $list.ForeColor=[Drawing.Color]::White
$list.BorderStyle='None'; $list.HeaderStyle='Nonclickable'
[void]$list.Columns.Add('COMPONENTE',190)
[void]$list.Columns.Add('STATO',230)
[void]$list.Columns.Add('OPERAZIONE',430)
$form.Controls.Add($list)
$progress=New-Object Windows.Forms.ProgressBar
$progress.SetBounds(32,432,876,7); $progress.Style='Marquee';$progress.MarqueeAnimationSpeed=25
$form.Controls.Add($progress)
$log=New-Object Windows.Forms.RichTextBox
$log.SetBounds(32,454,876,155)
$log.BackColor=[Drawing.ColorTranslator]::FromHtml('#0B1925')
$log.ForeColor=$muted; $log.ReadOnly=$true; $log.BorderStyle='None'
$log.Font=New-Object Drawing.Font('Consolas',9)
$log.Text='Verifica dei prerequisiti e integrita del setup...'
$form.Controls.Add($log)
$install=New-Object Windows.Forms.Button
$install.Text='INSTALLA M3PRO';$install.SetBounds(680,633,228,45)
$install.FlatStyle='Flat';$install.BackColor=$teal;$install.ForeColor=$dark
$install.Font=New-Object Drawing.Font('Segoe UI',11,[Drawing.FontStyle]::Bold)
$install.Enabled=$false
$form.Controls.Add($install)
$check=New-Object Windows.Forms.Button
$check.Text='Ricontrolla PC';$check.SetBounds(32,633,155,45)
$check.FlatStyle='Flat';$check.ForeColor=$muted
$form.Controls.Add($check)
$verify=New-Object Windows.Forms.Button
$verify.Text='Verifica download';$verify.SetBounds(199,633,165,45)
$verify.FlatStyle='Flat';$verify.ForeColor=$muted
$form.Controls.Add($verify)
$note=New-Object Windows.Forms.Label
$note.Text='Licenza e accesso Tailscale si completano dopo il setup. Eventuali driver richiedono conferma.'
$note.Font=New-Object Drawing.Font('Segoe UI',8)
$note.ForeColor=$muted;$note.SetBounds(32,690,876,22)
$form.Controls.Add($note)
function Start-SetupJob([string]$RequestedMode) {
    if ($script:worker -and -not $script:worker.HasExited) { return }
    $script:sequence++;$script:mode=$RequestedMode;$script:lastLog=''
    $script:stdout=Join-Path $jobRoot ("out-$($script:sequence).txt")
    $script:stderr=Join-Path $jobRoot ("err-$($script:sequence).txt")
    $install.Enabled=$false;$check.Enabled=$false;$verify.Enabled=$false
    $progress.Style='Marquee';$progress.MarqueeAnimationSpeed=25
    $stage.Text = switch ($RequestedMode) {'check' {'Controllo dei componenti del PC...'} 'verify' {'Verifica della release ufficiale e del download...'} default {'Installazione M3PRO in corso...'}}
    $flags = switch ($RequestedMode) {'check' {' -ChecklistOnly'} 'verify' {' -CheckOnly'} default {''}}
    try {
        $script:worker=Start-Process -FilePath "$env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe" -ArgumentList ('-NoProfile -ExecutionPolicy Bypass -File "'+$engine+'" -StatusFile "'+$statusFile+'"'+$flags) -WindowStyle Hidden -RedirectStandardOutput $script:stdout -RedirectStandardError $script:stderr -PassThru
        $null=$script:worker.Handle
    } catch {
        $stage.Text='Avvio non riuscito';$log.Text=$_.Exception.Message
        $check.Enabled=$true;$verify.Enabled=$true;$progress.Style='Blocks'
    }
}
function Refresh-SetupView {
    if (Test-Path $statusFile) {
        try {
            $state=Get-Content -LiteralPath $statusFile -Raw | ConvertFrom-Json
            $list.BeginUpdate();$list.Items.Clear()
            $script:machinePresent=$false
            foreach($row in $state.checklist) {
                $item=New-Object Windows.Forms.ListViewItem([string]$row.Componente)
                [void]$item.SubItems.Add([string]$row.Stato);[void]$item.SubItems.Add([string]$row.Azione)
                if ($row.Stato -eq 'PRESENTE' -or $row.Stato -eq 'OK') {$item.ForeColor=$teal}
                elseif ($row.Stato -eq 'MANCANTE') {$item.ForeColor=[Drawing.Color]::Gold}
                if ($row.Componente -eq 'M3 installato' -and $row.Stato -like 'PRESENTE*') {$script:machinePresent=$true}
                [void]$list.Items.Add($item)
            }
            $list.EndUpdate()
        } catch {}
    }
    $text=''
    foreach($file in @($script:stdout,$script:stderr)) {
        if($file -and (Test-Path $file)) {try {$text += [IO.File]::ReadAllText($file)+"`r`n"}catch{}}
    }
    if($text -and $text -ne $script:lastLog) {
        $script:lastLog=$text
        $log.Text=$text.Substring([Math]::Max(0,$text.Length-18000))
        $log.SelectionStart=$log.TextLength;$log.ScrollToCaret()
        if ($script:mode -eq 'install') {
            $steps=@($text -split "`n" | Where-Object {$_ -match '^(Scarico|Verificata release|Preparo ambiente|Installazione prerequisito|M3PRO .*avviato)'})
            if($steps.Count){$stage.Text=$steps[-1].Trim()}
        }
    }
    if($script:worker -and $script:worker.HasExited) {
        $script:worker.WaitForExit();$exitCode=$script:worker.ExitCode;$script:worker.Dispose();$script:worker=$null
        $progress.Style='Blocks';$progress.Value=0
        $check.Enabled=$true;$verify.Enabled=$true
        $script:readyForInstall=($exitCode -eq 0)
        if($exitCode -ne 0){$stage.Text='Operazione non completata - consulta il dettaglio qui sotto';$stage.ForeColor=[Drawing.Color]::Salmon}
        elseif($script:mode -eq 'install'){$stage.Text='M3PRO avviato - controlla il riepilogo dei componenti';$stage.ForeColor=$teal;$progress.Value=100}
        elseif($script:machinePresent){$stage.Text='M3 gia presente: per aggiornare usa il pulsante Update nell app';$stage.ForeColor=$teal}
        elseif($script:mode -eq 'verify'){$stage.Text='Pacchetto ufficiale verificato. Puoi procedere con il setup.';$stage.ForeColor=$teal}
        else{$stage.Text='Checklist pronta. Installa M3PRO per continuare.';$stage.ForeColor=[Drawing.Color]::White}
        $install.Enabled=($script:readyForInstall -and -not $script:machinePresent -and -not $CheckOnly)
    }
}
$timer=New-Object Windows.Forms.Timer
$timer.Interval=700;$timer.Add_Tick({Refresh-SetupView})
$check.Add_Click({Start-SetupJob 'check'})
$verify.Add_Click({Start-SetupJob 'verify'})
$install.Add_Click({Start-SetupJob 'install'})
$form.Add_FormClosing({param($sender,$e) if($script:worker -and -not $script:worker.HasExited){$e.Cancel=$true;[Windows.Forms.MessageBox]::Show('Operazione in corso. Attendi la conclusione prima di chiudere.','M3PRO Setup') | Out-Null}})
if ($PreviewPath) {
    Start-SetupJob 'check'
    while($script:worker){Start-Sleep -Milliseconds 200;Refresh-SetupView}
    $form.Show();[Windows.Forms.Application]::DoEvents();$form.PerformLayout()
    $bitmap=New-Object Drawing.Bitmap($form.Width,$form.Height)
    $form.DrawToBitmap($bitmap,(New-Object Drawing.Rectangle(0,0,$form.Width,$form.Height)))
    $bitmap.Save($PreviewPath,[Drawing.Imaging.ImageFormat]::Png);$bitmap.Dispose();$form.Dispose()
    Write-Output $PreviewPath
    exit 0
}
$form.Add_Shown({$timer.Start();Start-SetupJob 'check'})
[void]$form.ShowDialog()
$timer.Stop();$timer.Dispose();$form.Dispose()

